### PR TITLE
Update UI and content in landing page

### PR DESCRIPTION
**Pull request by OHR2328**

### CODE REVIEW

**Comment by chaitanyabaranwal** [comment]
Hello @OHR2328! Thanks for making this change, the website looks good :) I just had a few comments and wanted to check if it would be possible to:

- Have white text whenever the background is blue, it looks clearer that way.
- Increase the size of the screenshots, currently the look very small.

Once those changes are done, you can make a commit to this same branch and I can take a look and merge :)

**Comment by OHR2328** [comment]
okay will look into it and commit once I done the changes.

**Comment by chaitanyabaranwal** [comment]
Looks good to me, we can merge this 🚢

**Review by chaitanyabaranwal — APPROVED** [review]
Looks good to me, we can merge this 🚢

**Pull request merged**
